### ISSUE TITLE
can the current code run with your results?

### ISSUE THREAD

**Issue by Dongshengjiang** [rvorias/ind_knn_ad#1]
can the current code run with your results?

**Comment by rvorias** [comment]
Hi! I don't fully understand your question. Are you getting any errors?

In any case, I removed the cuda specifications in `requirements.txt`.
It might take a while before the dataset is downloaded and unpacked. I will try to add a progress bar.

**Comment by Dongshengjiang** [comment]
thanks for your repid reply. I can run your code now.
