### ISSUE TITLE
PADIM method consumes too much memory

### ISSUE THREAD

**Issue by Mshz2** [rvorias/ind_knn_ad#13]
Hi there,

I am using the pipeline based on the padim method and backbone_name="wide_resnet50_2". However, I see excessive raise in my memory when I check it with ``htop`` command in another terminal. I don't have same experience with spade method.
<img width="690" alt="Capture2" src="https://user-images.githubusercontent.com/63469924/132007727-08bad0f0-c0be-4caa-9127-4536ac5291af.PNG">

As picture shows, it consumes up to 121G in the memory. I even tried to reduce the 'd_reduced' parameter, but it is still around 100G. May I ask about your opinion how can I make it better? did U also faced same issue?

Best

**Comment by rvorias** [comment]
Djezus!

First of all, I shed some light on memory issues and possible solutions here: https://github.com/rvorias/ind_knn_ad/issues/8#issuecomment-902633484

What dataset are you using? If custom, how many training samples are in there?

**Comment by Mshz2** [comment]
> Djezus!
> 
> First of all, I shed some light on memory issues and possible solutions here: [#8 (comment)](https://github.com/rvorias/ind_knn_ad/issues/8#issuecomment-902633484)
> 
> What dataset are you using? If custom, how many training samples are in there?

I am using 2100 custom 348*348 resolution dataset.

**Comment by rvorias** [comment]
For such a dataset, you'd need to do an online calculation for mean and the cov matrix.

Atm I don't have time to implement that, but I'm open to PRs!

**Comment by rvorias** [comment]
I think you will run into trouble for every method. Maybe you can try it with a subset of the training images?

**Comment by Mshz2** [comment]
I just followed the [#8 (comment)](https://github.com/rvorias/ind_knn_ad/issues/8#issuecomment-902633484) and changed the backbone to ``backbone_name="efficientnet_b0" `` and it worked 💯  memory reduced to approx 20G (from 100G). Next I will just reduce the dataset size :) Thanks a lot
