### ISSUE TITLE
Is Mask required for training

### ISSUE THREAD

**Issue by Mshz2** [rvorias/ind_knn_ad#17]
Hi, thanks  for your efforts and fast responses.

At the question below, the final goal is only to get the anomaly score and not interested into the heatmap visualization.

I was checking the [model.py](https://github.com/rvorias/ind_knn_ad/blob/57de628b334f9dd62316ac7770db6e963b71ee8e/indad/models.py#L57) and I noticed that the created mask by us as the ground truth is only required during evaluation (and only for pixel_rocauc measurement) and not utilized for training (model.fit), am I right?

>   for sample, mask, label in tqdm(test_dl, **get_tqdm_params()):
			  z_score, fmap = self.predict(sample)
			  
			  image_preds.append(z_score.numpy())
			  image_labels.append(label)
			  
			  pixel_preds.extend(fmap.flatten().numpy())
			  pixel_labels.extend(mask.flatten().numpy())
			  
		  image_preds = np.stack(image_preds)
  
		  image_rocauc = roc_auc_score(image_labels, image_preds)
		  pixel_rocauc = roc_auc_score(pixel_labels, pixel_preds)
		  return image_rocauc, pixel_rocauc

So, if I completely eliminate the ground_truth mask dataloading from the all pipelines and I  only do `image_rocauc= model.evaluate(test_ds)` instead of `image_rocauc, pixel_rocauc = model.evaluate(test_ds)`,  can I still get only the anomaly score from image_rocauc without any mask labeling (have a complete unsupervised pipeline)?

Best

**Comment by rvorias** [comment]
Yeah that's possible. You will have to modify `evaluate` and `MVTecTestDataset` such that it does not return a mask.
