### ISSUE TITLE
Model Save&Load&Test

### ISSUE THREAD

**Issue by caglarerennn** [rvorias/ind_knn_ad#18]
How can I model save, model load and model test for one image? 

PATH = '/home/agteks/Desktop/ind_knn_ad/model.pt'
model = PatchCore(f_coreset= .01, backbone_name= "efficientnet_b0", coreset_eps= .95)

model.load_state_dict(torch.load('/home/agteks/Desktop/ind_knn_ad/model.pt'))
model.eval()
model = model.to('cuda')

        
#sample, *_ = test_dataset[st.session_state.test_idx]
pil_img = Image.open("/home/agteks/Desktop/ind_knn_ad/datasets/fabric_4/test/broken_large/Cropped_2_276_46_768.png")
pil_img = pil_img.resize((224, 224))
pil_to_tensor = transforms.ToTensor()(pil_img).unsqueeze_(0)
img_lvl_anom_score, pxl_lvl_anom_score = model.predict(pil_to_tensor)
score_range = pxl_lvl_anom_score.min(), pxl_lvl_anom_score.max()
show_pred(pil_to_tensor, img_lvl_anom_score, pxl_lvl_anom_score)

-- This code not working. Please help me :(

**Comment by rvorias** [comment]
What does the error say?

**Comment by caglarerennn** [comment]
TypeError: 'NoneType' object is not callable

**Comment by rvorias** [comment]
Can you give more logging information? I'm not sure all of the parts will be saved to the state dict.

**Comment by Mshz2** [comment]
> How can I model save, model load and model test for one image?
> 
> PATH = '/home/agteks/Desktop/ind_knn_ad/model.pt' model = PatchCore(f_coreset= .01, backbone_name= "efficientnet_b0", coreset_eps= .95)
> 
> model.load_state_dict(torch.load('/home/agteks/Desktop/ind_knn_ad/model.pt')) model.eval() model = model.to('cuda')
> 
> #sample, *_ = test_dataset[st.session_state.test_idx] pil_img = Image.open("/home/agteks/Desktop/ind_knn_ad/datasets/fabric_4/test/broken_large/Cropped_2_276_46_768.png") pil_img = pil_img.resize((224, 224)) pil_to_tensor = transforms.ToTensor()(pil_img).unsqueeze_(0) img_lvl_anom_score, pxl_lvl_anom_score = model.predict(pil_to_tensor) score_range = pxl_lvl_anom_score.min(), pxl_lvl_anom_score.max() show_pred(pil_to_tensor, img_lvl_anom_score, pxl_lvl_anom_score)
> 
> -- This code not working. Please help me :(

You need to return some of the variables of the model.fit() function inside the method objects (child objects inside the model.py) and save them by like torch.save. You can find out which variable are required to be saved within the predict function of that method and see which of them are called from the fit function of method.

for example for padim inside the model.py, you should do sth like this: 

class PaDiM(KNNExtractor):
....
def fit(self, train_dl):
..
return self.resize, self.r_indices, self.means_reduced, self.E_inv, self.image_size
def predict(self, sample, resize, r_indices, means_reduced, E_inv, image_size):
		self.resize = resize
		self.r_indices = r_indices
		self.means_reduced = means_reduced
		self.E_inv = E_inv
		self.image_size = image_size

And then within the run.py you should do
tobesaved = model.fit(train_ds)
torch.save(tobesaved, 'path.tar')
torch.save(model.state_dict(), 'path')

And during inference:
model.load_state_dict(torch.load('path')
var1, var2, var3, var4, var5 = torch.load('path.tar')
output= model.predict(test_img_tensor, var1, var2, var3, var4, var5)


If you wanna do model.evaluate(test_ds) like the repo, you should make the parent class KNNExtractor(torch.nn.Module) receives these variables for its evaluate function and the model.predict() inside of it

**Comment by rvorias** [comment]
Thanks for the comment, Mshz2. Closing this for now.
