### ISSUE TITLE
What's the neighbourhood size In PathCore implementations?

### ISSUE THREAD

**Issue by mjack3** [rvorias/ind_knn_ad#22]
Hello and thank for your contribution. Really good job

Trying your code i am wondering if [this attribute n_reweight](https://github.com/rvorias/ind_knn_ad/blob/57de628b334f9dd62316ac7770db6e963b71ee8e/indad/models.py#L243) is the neighbourhood size described in the Paper.

**Comment by rvorias** [comment]
Hi,

No, the neighbourhood size is defined at https://github.com/rvorias/ind_knn_ad/blob/57de628b334f9dd62316ac7770db6e963b71ee8e/indad/models.py#L241

We use the averaging to combined information of neighbouring patches. In this case the neighbourhood kernel is of size 3.

**Comment by mjack3** [comment]
Hello, thanks for your answer. I did a mistake in my question, I would like to where is defined the value of "b nearest patch-features"

**Comment by rvorias** [comment]
Yes, `n_reweight` = `b` in the paper.

**Comment by mjack3** [comment]
Thanks! to close this issue, I would appreciate to do a last question. In README section I see this about PatchCore 

`* actually does not have any knn mechanism, but shares many things implementation-wise.` 

is KNN implemented? If not, maybe I could make a develop

**Comment by rvorias** [comment]
Hmm, I just realize that it actually DOES have a KNN mechanism: when it compares a new patch to it's existing database.

So thanks for your suggestions, but it is not needed ^^

**Comment by rvorias** [comment]
That is actually a note on Padim, not PatchCore.
