### ISSUE TITLE
New performance and improvement int patchcore

### ISSUE THREAD

**Issue by mjack3** [rvorias/ind_knn_ad#23]
Hello.

I tested your Patchcore implementation and i need to advice you of a mistake of what the table of results shows
I tested your implementation for 1% of coreset with different B values to get the mean as final results

![image](https://user-images.githubusercontent.com/37028633/149622418-abede435-af5b-42e5-a923-1c85d237db69.png)

You can see, that the performance is better than what you described in your table.

Moreover, if we use avgpooling (3, 1, 1) instead avgpooling(3, 2, 0)  with Interpolation Lanzcos in the training, results are still better. In fact, paper says that increasing the stride decreases the performance

![image](https://user-images.githubusercontent.com/37028633/149622653-f58e7e4e-ed7f-473c-8384-b449f1c8c40e.png)

Here is the results of using this new avgpooling

![image](https://user-images.githubusercontent.com/37028633/149622448-a73fb759-aea0-4391-8b32-855a579faa8b.png)

**Comment by rvorias** [comment]
Cool, thanks for you comments! Those gains are pretty significant.
I didn't play too much with `b`, didn't know it would work that well.

Hmm I thought I already use (3,1,1).

Anyway, if you want you can submit a PR!

**Comment by mjack3** [comment]
Thanks i will
