### ISSUE TITLE
Would you add FastFlow?

### ISSUE THREAD

**Issue by mjack3** [rvorias/ind_knn_ad#26]

**Comment by rvorias** [comment]
I got a dev branch locally for it, but very difficult to reproduce. Don’t
trust the all the paperswithcode results until it is reproducible ;)

**Comment by mjack3** [comment]
I'm also developing the fastflow model. I have a WIP version that gets near results (- 0.5).

It's difficult replicate because paper has incongruences and It doesn't provide implementation details.

If you wish, we can cooperate

**Comment by rvorias** [comment]
Closing this for now because I don't think we'll implement FastFlow any time soon.
