### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by fIomingo** [rvorias/ind_knn_ad#27]
Hey the app is currently not responding

by the way do you have a tutorial how can i make the app run on a windows maschine? im new to maschine learning and want to test anomaly detection on pictures of industrial parts.

**Comment by rvorias** [comment]
Thanks for letting me know! Hmm in theory everything should work save the bash files. But if you want more batteries included, try https://github.com/openvinotoolkit/anomalib
