### ISSUE TITLE
PaDiM performance in README is wrong

### ISSUE THREAD

**Issue by Howeng98** [rvorias/ind_knn_ad#30]
Where do you get the PaDiM detection data in AUROC in the README table?

From the official paper, there are no provide detailed categories DET AUROC score but only provides DET AUROC total mean score with WR50_2 backbone (95.3) at most. How did you get an overall 97.5 in PaDiM paper performance in Anomaly Detection in README table?

I assume that you copy the wrong data into the README table from the paper, which you copy Localization AUROC into Image-level table and Localization AUPRO into Pixel level table.

Thanks

**Comment by rvorias** [comment]
Hi! Thanks for verifying the data!

You are right. I'll adapt the table.
