### ISSUE TITLE
How to save the model as a checkpoint file / load model from a checkpoint file for training and predicting?

### ISSUE THREAD

**Issue by FirokOtaku** [rvorias/ind_knn_ad#31]
It seems that code in `cli_interface()` would train on a pre-trained model and does not interact to filesystem?

Could you please give an example show how to do that or add more parameters to `cli_interface()`?

**Comment by rvorias** [comment]
Check the commit above on how to add more params.

For loading and saving, the timm library has been absorbed in the huggingface ecosystem.
Check the docs here: https://huggingface.co/docs/timm/index and if you find and loading/saving, I can try to integrate it.
