### ISSUE TITLE
is it necessary to install "faiss"

### ISSUE THREAD

**Issue by kazu114** [rvorias/ind_knn_ad#32]
Hi,
this repo is great and very  helpful !!

I have one question to ask.

I could run the program fine without installing "faiss". 
So I am just wondering what is the purpose of using "faiss" in the program. 
will the inference speed increase if using "faiss"?

Thanks

**Comment by rvorias** [comment]
Hi! Thanks!

The faiss library is useful when you want to save a bunch of embedding tensors (during training) and want to compare against a new embedding (during inference). For the datasets and hyperparams in this repo, I've been able to get away with custom distance implementations.

However if the datasets become very large or if you want to get the best (cpu) performance, faiss is probably needed.
