### ISSUE TITLE
Request for an Updated Version Due to Compatibility Issues

### ISSUE THREAD

**Issue by fradiii** [rvorias/ind_knn_ad#33]
Hello,

Could I please get an updated version of this project? Many features are not working correctly and there are compatibility issues that I am unable to resolve. As a beginner, I have been trying to fix these problems for the past two months without success. I am currently an intern and this is my first year, so I really need help with this.

Thank you very much for your assistance.

Best regards,

**Comment by rvorias** [comment]
Hey, please give some more info what exactly is going wrong.

In the meantime I released the versions of the requirements, it was indeed failing to install.
Also fixed dataset downloading.

Should be good to go atm.

**Comment by fradiii** [comment]
Hi,

Yes, the versions of the requirements and dataset downloading issues are fixed, but you need to update the streamlit_app.py file as it is not functioning correctly.

**Comment by rvorias** [comment]
Haha I was afraid you were going to mention that. I'll take a look.

**Comment by fradiii** [comment]
Thank you! I appreciate it. ^-^

**Comment by rvorias** [comment]
Fixed dependencies. Rerunning `pip install -r requirements.txt` should do the trick.
